<!DOCTYPE html>
<html>
<head>
<title>Welcome Letter</title>
</head>
<body>
	<img alt="logo" src="cid:image01">

	<h3>Sr. Administrador,</h3>

	<p>No se ha producido el evento para su replicación, debido a que el objeto no admite Replica Inmediata en este momento. Se solicita réplica manual.</p>
	<p>Sistema: ${contexto}</p>
	<p>Detalle: ${detalle}</p>
	<p>Regards</p>
	<p>Grupo Arinfotica.com</p>
</body>
</html>